import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { Roboto_Condensed } from "next/font/google";
import Footer from "@/components/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { KindeClientProvider } from "@/providers/KindeClientProvider";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { SearchContextProvider } from "@/context/SearchContext";

const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser, isAuthenticated } = getKindeServerSession();
  const user = await getUser(); // type: KindeUser | null
  const isLoggedIn = await isAuthenticated(); // type: boolean

  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <div className="flex flex-col min-h-screen">
          <SearchContextProvider>
            <NavigationBar user={user} isLoggedIn={isLoggedIn} />
            <SidebarProvider>
              <AppSidebar />
              <main className="flex grow">
                <SidebarTrigger />
                <KindeClientProvider>{children}</KindeClientProvider>
              </main>
            </SidebarProvider>
          </SearchContextProvider>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
